version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=invite_system
      - JWT_SECRET=change-this-in-production
      - INVITE_CODE_SECRET=change-this-in-production
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=invite_system
    volumes:
      - postgres-invite:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-invite:

